/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 54HsYifXcmbnw5veKzJ3R2
// Component: VO-JOznlsGEg
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv
} from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import { usePlasmicInvalidate } from "@plasmicapp/react-web/lib/data-sources";
import { Timer } from "@plasmicpkgs/plasmic-basic-components";
import { DataFetcher } from "@plasmicpkgs/plasmic-query";
import Button from "../../Button"; // plasmic-import: q5yBY-eKZ0QK/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 54HsYifXcmbnw5veKzJ3R2/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 54HsYifXcmbnw5veKzJ3R2/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: VO-JOznlsGEg/css

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array("menu");

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "menuOpened",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "restApi",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return `${window.location.origin}/glances/api/4/`;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return ``;
              }
              throw e;
            }
          })()
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
          onLoad={async event => {
            const $steps = {};
            $steps["updateMenuOpened"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["menuOpened"]
                    },
                    operation: 0
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;
                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateMenuOpened"] != null &&
              typeof $steps["updateMenuOpened"] === "object" &&
              typeof $steps["updateMenuOpened"].then === "function"
            ) {
              $steps["updateMenuOpened"] = await $steps["updateMenuOpened"];
            }
          }}
        >
          <Timer
            data-plasmic-name={"timer"}
            data-plasmic-override={overrides.timer}
            className={classNames("__wab_instance", sty.timer)}
            intervalSeconds={2}
            isRunning={true}
            onTick={async () => {
              const $steps = {};
              $steps["refreshData"] = true
                ? (() => {
                    const actionArgs = {
                      queryInvalidation: ["plasmic_refresh_all"]
                    };
                    return (async ({ queryInvalidation }) => {
                      if (!queryInvalidation) {
                        return;
                      }
                      await plasmicInvalidate(queryInvalidation);
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["refreshData"] != null &&
                typeof $steps["refreshData"] === "object" &&
                typeof $steps["refreshData"].then === "function"
              ) {
                $steps["refreshData"] = await $steps["refreshData"];
              }
            }}
            runWhileEditing={false}
          />

          <div className={classNames(projectcss.all, sty.freeBox__kDdqt)}>
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.h1__54HsY,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {"Lantern"}
            </h1>
            <div className={classNames(projectcss.all, sty.freeBox__eRgrj)}>
              <div className={classNames(projectcss.all, sty.freeBox__mkib4)}>
                <DataFetcher
                  className={classNames(
                    "__wab_instance",
                    sty.httpRestApiFetcher__pqDh
                  )}
                  dataName={"fetchedData"}
                  errorDisplay={
                    <DataCtxReader__>
                      {$ctx => "Error fetching data"}
                    </DataCtxReader__>
                  }
                  errorName={"fetchError"}
                  loadingDisplay={
                    <DataCtxReader__>{$ctx => "Loading..."}</DataCtxReader__>
                  }
                  method={"GET"}
                  noLayout={false}
                  url={(() => {
                    try {
                      return $state.restApi + "cpu";
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                >
                  <DataCtxReader__>
                    {$ctx => (
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gQl8
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__wcfJw
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__t5Ghm
                              )}
                            >
                              {"CPU"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zutph
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return (
                                      $ctx.fetchedData.total.toFixed(0) + "%"
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "20%";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                          <DataFetcher
                            className={classNames(
                              "__wab_instance",
                              sty.httpRestApiFetcher__nrTdM
                            )}
                            dataName={"fetchedData"}
                            errorDisplay={
                              <DataCtxReader__>
                                {$ctx => "Error fetching data"}
                              </DataCtxReader__>
                            }
                            errorName={"fetchError"}
                            loadingDisplay={
                              <DataCtxReader__>
                                {$ctx => "Loading..."}
                              </DataCtxReader__>
                            }
                            method={"GET"}
                            noLayout={false}
                            url={(() => {
                              try {
                                return $state.restApi + "quicklook";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          >
                            <DataCtxReader__>
                              {$ctx => (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__tIkKv
                                  )}
                                >
                                  <React.Fragment>
                                    {$ctx.fetchedData.cpu_name}
                                  </React.Fragment>
                                </div>
                              )}
                            </DataCtxReader__>
                          </DataFetcher>
                        </div>
                        <DataFetcher
                          className={classNames(
                            "__wab_instance",
                            sty.httpRestApiFetcher__hDgFa
                          )}
                          dataName={"fetchedData"}
                          errorDisplay={
                            <DataCtxReader__>
                              {$ctx => "Error fetching data"}
                            </DataCtxReader__>
                          }
                          errorName={"fetchError"}
                          loadingDisplay={
                            <DataCtxReader__>
                              {$ctx => "Loading..."}
                            </DataCtxReader__>
                          }
                          method={"GET"}
                          noLayout={false}
                          url={(() => {
                            try {
                              return $state.restApi + "sensors";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                        >
                          <DataCtxReader__>
                            {$ctx => (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___6L2Er
                                )}
                              >
                                <React.Fragment>
                                  {$ctx.fetchedData[0].value + "\xB0C"}
                                </React.Fragment>
                              </div>
                            )}
                          </DataCtxReader__>
                        </DataFetcher>
                      </React.Fragment>
                    )}
                  </DataCtxReader__>
                </DataFetcher>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__gkyVn)}>
                <DataFetcher
                  className={classNames(
                    "__wab_instance",
                    sty.httpRestApiFetcher__wOYpM
                  )}
                  dataName={"fetchedData"}
                  errorDisplay={
                    <DataCtxReader__>
                      {$ctx => "Error fetching data"}
                    </DataCtxReader__>
                  }
                  errorName={"fetchError"}
                  loadingDisplay={
                    <DataCtxReader__>{$ctx => "Loading..."}</DataCtxReader__>
                  }
                  method={"GET"}
                  noLayout={false}
                  url={(() => {
                    try {
                      return $state.restApi + "mem";
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                >
                  <DataCtxReader__>
                    {$ctx => (
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___5U5A8
                          )}
                        >
                          {"RAM"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pciP6
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return (
                                  $ctx.fetchedData.percent.toFixed(1) + "%"
                                );
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "1.8/8.0GiB";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wctR1
                          )}
                        >
                          <React.Fragment>{`${($ctx.fetchedData.used / 1073741824).toFixed(2)} / ${($ctx.fetchedData.total / 1073741824).toFixed(2)} GB`}</React.Fragment>
                        </div>
                      </React.Fragment>
                    )}
                  </DataCtxReader__>
                </DataFetcher>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__xfPhy)}>
                <DataFetcher
                  className={classNames(
                    "__wab_instance",
                    sty.httpRestApiFetcher___7Aqt6
                  )}
                  dataName={"fetchedData"}
                  errorDisplay={
                    <DataCtxReader__>
                      {$ctx => "Error fetching data"}
                    </DataCtxReader__>
                  }
                  errorName={"fetchError"}
                  loadingDisplay={
                    <DataCtxReader__>{$ctx => "Loading..."}</DataCtxReader__>
                  }
                  method={"GET"}
                  noLayout={false}
                  url={(() => {
                    try {
                      return $state.restApi + "fs";
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                >
                  <DataCtxReader__>
                    {$ctx => (
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iXvU
                          )}
                        >
                          {"DISK"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__i3M8T
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return (
                                  $ctx.fetchedData[0].percent.toFixed(1) + "%"
                                );
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "20%";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nSyqy
                          )}
                        >
                          <React.Fragment>{`${($ctx.fetchedData[0].used / 1073741824).toFixed(2)} / ${($ctx.fetchedData[0].size / 1073741824).toFixed(2)} GB`}</React.Fragment>
                        </div>
                      </React.Fragment>
                    )}
                  </DataCtxReader__>
                </DataFetcher>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__un2Gv)}>
              <div className={classNames(projectcss.all, sty.freeBox__o17CH)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0OAz
                  )}
                >
                  {"Containers"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dSn2Q
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return undefined;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "5 running \u00b7 1 stopped";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </div>
              <DataFetcher
                className={classNames(
                  "__wab_instance",
                  sty.httpRestApiFetcher___2Uxlg
                )}
                dataName={"fetchedData"}
                errorDisplay={
                  <DataCtxReader__>
                    {$ctx => "Error fetching data"}
                  </DataCtxReader__>
                }
                errorName={"fetchError"}
                loadingDisplay={
                  <DataCtxReader__>{$ctx => "Loading..."}</DataCtxReader__>
                }
                method={"GET"}
                noLayout={false}
                url={(() => {
                  try {
                    return $state.restApi + "containers";
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
              >
                <DataCtxReader__>
                  {$ctx =>
                    (_par =>
                      !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                      (() => {
                        try {
                          return $ctx.fetchedData;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return [];
                          }
                          throw e;
                        }
                      })()
                    ).map((__plasmic_item_0, __plasmic_idx_0) => {
                      const currentItem = __plasmic_item_0;
                      const currentIndex = __plasmic_idx_0;
                      return (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oOyz6
                          )}
                          key={currentIndex}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__gcZBg
                            )}
                          >
                            <Button
                              data-plasmic-name={"button"}
                              data-plasmic-override={overrides.button}
                              className={classNames(
                                "__wab_instance",
                                sty.button
                              )}
                              color={(() => {
                                try {
                                  return currentItem.status === "restarting"
                                    ? "warning"
                                    : currentItem.status === "stopped"
                                      ? "danger"
                                      : "success";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })()}
                              label={
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__eE29L
                                  )}
                                >
                                  {""}
                                </div>
                              }
                              roundedFull={true}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__m8SHm
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return currentItem.name;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "jellyfin";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ybhF5
                              )}
                            >
                              <React.Fragment>
                                {currentItem.cpu_percent !== null
                                  ? currentItem.cpu_percent.toFixed(0) + "% CPU"
                                  : "--"}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hyM8
                              )}
                            >
                              <React.Fragment>
                                {currentItem.memory.usage
                                  ? `${(currentItem.memory.usage / (1024 * 1024 * 1024)).toFixed(2)} GB`
                                  : "--"}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___6Ex8J
                              )}
                            >
                              <React.Fragment>
                                {currentItem.ports === ""
                                  ? "--"
                                  : currentItem.ports}
                              </React.Fragment>
                            </div>
                          </div>
                        </div>
                      );
                    })
                  }
                </DataCtxReader__>
              </DataFetcher>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "timer", "h1", "button"],
  timer: ["timer"],
  h1: ["h1"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    timer: makeNodeComponent("timer"),
    h1: makeNodeComponent("h1"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
