/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 54HsYifXcmbnw5veKzJ3R2
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsn52Vg6ILnweu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: n52VG6iLnweu/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsn52Vg6ILnweu
});
